# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\hw1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 422)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
       
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(80, 20, 250, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label1_1")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 185, 350, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label1_2")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 20, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label1_3")


        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 20, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")


        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(380, 50, 200, 350))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.btn3_2 = QtWidgets.QPushButton(self.frame_3)
        self.btn3_2.setGeometry(QtCore.QRect(35, 70, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn3_2.setFont(font)
        self.btn3_2.setObjectName("btn1_2")
        self.btn3_1 = QtWidgets.QPushButton(self.frame_3)
        self.btn3_1.setGeometry(QtCore.QRect(35, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn3_1.setFont(font)
        self.btn3_1.setObjectName("btn1_1")
        self.btn3_4 = QtWidgets.QPushButton(self.frame_3)
        self.btn3_4.setGeometry(QtCore.QRect(35, 300, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn3_4.setFont(font)
        self.btn3_4.setObjectName("btn1_4")
        self.frame_3_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_3_2.setGeometry(QtCore.QRect(15, 135, 171, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame_3_2.setFont(font)
        self.frame_3_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3_2.setObjectName("frame_3_2")
        self.btn3_3 = QtWidgets.QPushButton(self.frame_3_2)
        self.btn3_3.setGeometry(QtCore.QRect(30, 90, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn3_3.setFont(font)
        self.btn3_3.setObjectName("btn1_3")
        self.label_6 = QtWidgets.QLabel(self.frame_3_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.cboxImgNum = QtWidgets.QComboBox(self.frame_3_2)
        self.cboxImgNum.setGeometry(QtCore.QRect(10, 50, 151, 31))
        self.cboxImgNum.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cboxImgNum.setObjectName("cboxImgNum")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(600, 50, 250, 70))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.btn4 = QtWidgets.QPushButton(self.frame_4)
        self.btn4.setGeometry(QtCore.QRect(15, 15, 211, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn4.setFont(font)
        self.btn4.setObjectName("btn4")

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setGeometry(QtCore.QRect(70, 50, 250, 130))
        self.frame_1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_1.setObjectName("frame_1")
        self.btn1_1 = QtWidgets.QPushButton(self.frame_1)
        self.btn1_1.setGeometry(QtCore.QRect(15, 15, 211, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn1_1.setFont(font)
        self.btn1_1.setObjectName("btn1_1")
        self.btn1_2 = QtWidgets.QPushButton(self.frame_1)
        self.btn1_2.setGeometry(QtCore.QRect(15, 70, 211, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn1_2.setFont(font)
        self.btn1_2.setObjectName("btn1_1")

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(70, 220, 250, 180))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.btn2_1 = QtWidgets.QPushButton(self.frame_2)
        self.btn2_1.setGeometry(QtCore.QRect(15, 15, 211, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn2_1.setFont(font)
        self.btn2_1.setObjectName("btn2_1")
        self.btn2_2 = QtWidgets.QPushButton(self.frame_2)
        self.btn2_2.setGeometry(QtCore.QRect(15, 70, 211, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn2_2.setFont(font)
        self.btn2_2.setObjectName("btn2_2")
        self.btn2_3 = QtWidgets.QPushButton(self.frame_2)
        self.btn2_3.setGeometry(QtCore.QRect(15, 125, 211, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn2_3.setFont(font)
        self.btn2_3.setObjectName("btn2_3")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "1. Histogram Equalization "))
        self.label_2.setText(_translate("MainWindow", "2. Hough Circle Transform and Histogram "))
        self.label_3.setText(_translate("MainWindow", "3. Camera Calibration "))
        self.label_4.setText(_translate("MainWindow", "4. Augmented Reality"))

        self.btn1_1.setText(_translate("MainWindow", "1.1 Original image histogram"))
        self.btn1_2.setText(_translate("MainWindow", "1.2 Equalized image histogram"))
        self.btn2_1.setText(_translate("MainWindow", "2.1 Hough circle"))
        self.btn2_2.setText(_translate("MainWindow", "2.2 Hue histogram"))
        self.btn2_3.setText(_translate("MainWindow", "2.3 Back projection"))
        self.btn3_2.setText(_translate("MainWindow", "3.2 Intrinsic matrix"))
        self.btn3_1.setText(_translate("MainWindow", "3.1 Corner detection"))
        self.btn3_4.setText(_translate("MainWindow", "3.4 Distortion matrix"))
        self.btn3_3.setText(_translate("MainWindow", "3.3 Extrinsic matrix"))
        self.label_6.setText(_translate("MainWindow", "Select Image"))
        self.cboxImgNum.setItemText(0, _translate("MainWindow", "1"))
        self.cboxImgNum.setItemText(1, _translate("MainWindow", "2"))
        self.cboxImgNum.setItemText(2, _translate("MainWindow", "3"))
        self.cboxImgNum.setItemText(3, _translate("MainWindow", "4"))
        self.cboxImgNum.setItemText(4, _translate("MainWindow", "5"))
        self.cboxImgNum.setItemText(5, _translate("MainWindow", "6"))
        self.cboxImgNum.setItemText(6, _translate("MainWindow", "7"))
        self.cboxImgNum.setItemText(7, _translate("MainWindow", "8"))
        self.cboxImgNum.setItemText(8, _translate("MainWindow", "9"))
        self.cboxImgNum.setItemText(9, _translate("MainWindow", "10"))
        self.cboxImgNum.setItemText(10, _translate("MainWindow", "11"))
        self.cboxImgNum.setItemText(11, _translate("MainWindow", "12"))
        self.cboxImgNum.setItemText(12, _translate("MainWindow", "13"))
        self.cboxImgNum.setItemText(13, _translate("MainWindow", "14"))
        self.cboxImgNum.setItemText(14, _translate("MainWindow", "15"))
        self.btn4.setText(_translate(
            "MainWindow", "4. Augmented Reality"))
